version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: data-mapping-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=data-mapping-app
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: data-mapping-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/data-mapping
      - PORT=3001
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: data-mapping-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - GOOGLE_CLIENT_ID=903098848480-sie6acph9pdm41fner8cctvji86o0hd5.apps.googleusercontent.com
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  mongodb_data:
    driver: local
